SELECT
    -- [ALL | DISTINCT | DISTINCTROW ]
      -- [HIGH_PRIORITY]
      -- [STRAIGHT_JOIN]
      -- [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
      -- [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    ALL
    SELECT_EXPR1, SELECT_EXPR2-- SELECT_EXPR [, SELECT_EXPR ...]
    FROM TABLE_REFERENCES
      PARTITION (PARTITION_LIST)
    WHERE WHERE_CONDITION
    GROUP BY COL_NAME1 ASC, COL_NAME2 ASC-- {COL_NAME | EXPR | POSITION} [ASC | DESC], ... 
    	WITH ROLLUP
    HAVING WHERE_CONDITION
    ORDER BY COL_NAME1 ASC -- {COL_NAME | EXPR | POSITION} [ASC | DESC], ...
    LIMIT 1, 10 -- {[OFFSET,] ROW_COUNT | ROW_COUNT OFFSET OFFSET}
    -- PROCEDURE PROCEDURE_NAME(ARGUMENT_LIST) -- PROCEDURE syntax is deprecated as of MySQL 5.7.18, and is removed in MySQL 8.0.
    -- [INTO OUTFILE 'FILE_NAME' [CHARACTER SET CHARSET_NAME] EXPORT_OPTIONS
      -- | INTO DUMPFILE 'FILE_NAME'
      -- | INTO VAR_NAME [, VAR_NAME]]
    INTO OUTFILE 'FILE_NAME' CHARACTER SET UTF8MB4 FIELDS TERMINATED BY '\t'
    FOR UPDATE -- [FOR UPDATE | LOCK IN SHARE MODE]